version: 0.1

phases:
  install:
    commands:
    - echo Installing NPM modules...
    - aws s3 cp s3://us-east-1.artifacts.safeto.fail/NPM-CICD-Token/.npmrc .
    - npm install -g npm@latest
    - npm install
    - npm audit
  pre_build:
    commands:
    - echo Installing source NPM dependencies...
  build:
    commands:
    - echo Unit tests started at `date`
    - ln -s node_modules/jest/bin/jest.js jest
    - ./jest *
    - echo Unit tests completed at `date`
    - rm ./jest
    - npm prune --production
  post_build:
    commands:
    - echo Unit tests completed at `date`
artifacts:
  files:
  - '**/*'